name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create config file
        run: |
          echo "const config = { YOUTUBE_API_KEY: '${{ secrets.YOUTUBE_API_KEY }}' };" > config.js
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          - name: Debug Secret
          run: |
            if [ -z "${{ secrets.YOUTUBE_API_KEY }}" ]; then
              echo "Secret is empty or not accessible."
              exit 1
            else
              echo "Secret fetched successfully."
            fi
        